### ISSUE TITLE
Please create Resources page - Evangelism page on jakarta.ee

### ISSUE THREAD

**Issue by TanjaObradovic** [jakartaee/jakartaee.github.io#178] opened 2019-01-14 15:44 UTC
**Is your feature request related to a problem? Please describe.**

Please work with Thabang and marketing team for details on creating this page. the initial motivation was to collect all documents related to the EF and Jakarta EE Specification Process and publish it here.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ThabangMash** [comment] 2019-01-30 04:10
Please close this -- duplicate of https://github.com/jakartaee/jakartaee.github.io/issues/108

**Comment by chrisguindon** [comment] 2019-02-25 17:04
Closing as requested by @ThabangMash

**Closed by chrisguindon** 2019-02-25 17:04 UTC
